name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        apt update -y
        apt install -y software-properties-common
        add-apt-repository ppa:deki/firejail
        apt update -y
        apt install -y build-essential cmake firejail
    - name: Shards install
      run: shards install
    - name: Run tests
      run: crystal spec
