name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt update -y
        apt install -y build-essential cmake
        shards install
    - name: Manually build lexbor lib
      run: crystal lib/lexbor/src/ext/build_ext.cr
    - name: Run tests
      run: crystal spec
