name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        apt update -y
        apt install -y g++ cmake wget libapparmor-dev
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "netblue30/firejail"
        latest: true
        fileName: "*amd64.deb"
    - name: Install firejail
      run: apt install -y "./firejail_*"
    - name: Shards install
      run: shards install
    - name: Run tests
      run: LOG_LEVEL=error crystal spec
